<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec(" Alteração de cursos ");
?>

<FORM ACTION="/ed/webmaster/alunos/dbmatricula2.phtml" METHOD="post">      
<?PHP
	$conn = pg_connect("localhost", "5432", "", "", "ed");
	if(!$conn){
		echo "Não Foi possível abrir a base de dados";
		exit;
	}
	$result = pg_exec($conn, "select * from cursos where cod_curso = $codigo_curso;");
	$num = pg_numrows($result);
	if($num == 0){
		echo "<BR>Nada Encontrado."; 
 		echo "<BR><form><input type=\"button\" value=\"Retornar\" onClick=\"history.back()\"></form>";
		exit; 
	}
	echo "Nome do Curso :";
	echo "<INPUT TYPE=\"hidden\" NAME=\"codigo_curso\" VALUE=\"";
	echo pg_result($result, 0, "cod_curso"); echo "\">\n";	
	echo "<INPUT TYPE=\"hidden\" NAME=\"nome_curso\" VALUE=\"";
	echo pg_result($result, 0, "nome"); echo "\">\n";
	echo pg_result($result, 0, "nome");
    pg_FreeResult($result);  

    $result = pg_Exec($conn, "Select * from alunos_cursos WHERE cod_curso = $codigo_curso;");
    $num = pg_NumRows($result);
    if ( $num == 0 ) {
          MostraErro ("Não existem alunos cadastrados neste curso.");
     }
     echo "<BR>Selecione um Aluno:";
     echo "<SELECT NAME=\"codigo_aluno\">\n";
     for($i = 0; $i < $num; $i++)
     {
        $aux = pg_Result($result, $i, "cod_aluno");
    	$result1 = pg_Exec($conn, "Select * from alunos WHERE cod_aluno = '$aux';");
		$num_aux = pg_NumRows($result1);
		if ( $num_aux == 0 ) {
			MostraErro ("Não existem alunos cadastrados neste curso.");
	     }
		 $nome_aluno= pg_Result($result1, 0, "nome");
         echo "<OPTION VALUE=\"";
		 echo "$aux";
         /*echo pg_Result($result1, $i, "cod_aluno");*/
         echo "\">";
		 echo "$nome_aluno";
		 echo "</OPTION>";
         pg_FreeResult($result1);  
     }
     echo "</SELECT>\n";
     pg_FreeResult($result);  
     pg_Close($conn);


?>
<CENTER><INPUT TYPE="submit" VALUE="continuar"></CENTER>
</FORM>
<?PHP MostraRodape(); ?>
