<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec(" Inclusão de Alunos ");
?>

<FORM ACTION="/ed/webmaster/alunos/dbinclusao.phtml" METHOD="POST">
<?

	$conn = pg_Connect("localhost", "5432", "", "", "ed");
	     
	if (!$conn) {
		SaiErro ("Nao foi possivel abrir banco de dados.\n");
	}

    $result = pg_Exec($conn, "Select * from cursos_materias WHERE cod_curso = $codigo_curso;");
    $num = pg_NumRows($result);
	if ( $num == 0 ) {
		MostraErro ("Não existe matérias cadastradas nos cursos.");
	} 

    echo "<BR>Listagem de todas as matérias do curso:";
    echo "<TABLE BORDER = \"2\">";   
	echo "<TR><TD width=\"5\">Código curso</TD><TD>Curso</TD><TD>Data </TD><TD width=\"5\">Codigo matéria </TD><TD>Matéria</TD></TR>\n";
    for($i = 0; $i < $num; $i++) {
		$cod_curso= pg_Result($result, $i, "cod_curso");
		$data_aux= pg_Result($result, $i, "data_criacao_materia");
		$dmano=explode("-", $data_aux);
		$d = $dmano[0];
		$m = $dmano[1];
		$y = $dmano[2];
		$data_criacao_materia= date( "d-m-Y", mktime(0, 0, 0, $d, $m , $y));    
		$cod_materia= pg_Result($result, $i, "cod_materia");
		$resultnome = pg_exec($conn, "select * from cursos where cod_curso = $cod_curso;");
		$numaux = pg_numrows($resultnome);
		if($numaux == 0){
			echo "<BR>Nada Encontrado.";
			echo "<BR><form><input type=\"button\" value=\"Retornar\" onClick=\"history.back()\">";
			echo "</form>";
			exit;
		}        
		$nome_curso =  pg_result($resultnome, 0, "nome");
		pg_FreeResult($resultnome);   

		$resultnome = pg_exec($conn, "select * from materias where cod_materia = $cod_materia;");
		$numaux = pg_numrows($resultnome);
		if($numaux == 0){
			echo "<BR>Nada Encontrado.";
			echo "<BR><form><input type=\"button\" value=\"Retornar\" onClick=\"history.back()\">";
			echo "</form>";
			exit;
		}        
		$nome_materia =  pg_result($resultnome, 0, "nome");
		pg_FreeResult($resultnome);   

		echo "<TR><TD>";
		echo "$cod_curso";
		echo "</TD><TD>";
		echo "$nome_curso";
		echo "</TD><TD>";
		echo "$data_criacao_materia";
		echo "</TD><TD>";
		echo "$cod_materia";
		echo "</TD><TD>";
		echo "$nome_materia";
		echo "</TD></TR>";

    }
	echo "</TABLE>";
	echo "<INPUT TYPE=\"hidden\" NAME=\"codigo_curso\" VALUE=\"$codigo_curso\" ><BR>\n";
    pg_Close($conn);
    pg_FreeResult($result);
?>
<BR>
<P>Matricular em todas as matérias do curso? <BR>
<INPUT TYPE="radio" NAME="cadtodasmaterias"  VALUE="sim" checked>sim</INPUT> <BR>
<INPUT TYPE="radio" NAME="cadtodasmaterias" VALUE="nao">não, vou me cadastrar nas matérias depois.</INPUT>
<P>Nome :
<INPUT TYPE="text" NAME="nome_aluno" SIZE="40"></INPUT>
<P>Email :
<INPUT TYPE="text" NAME="email" SIZE="50"></INPUT>
<P>Chave de acesso: (login no sistema)
<INPUT TYPE="text" NAME="chave" SIZE="8"></INPUT>
<P>Senha de acesso:
<INPUT TYPE="password" NAME="senha" SIZE="8"></INPUT>
<CENTER>
<INPUT TYPE="submit" VALUE="Cadastrar"></INPUT>
<INPUT TYPE="reset" VALUE="Limpar"></INPUT>
</CENTER>
</FORM>

<?PHP MostraRodape(); ?>
