<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec("Alunos ");
?>
<H2>Operações</H2>
<HR>

<A HREF="/ed/webmaster/alunos/inclusao.phtml">Incluir novo aluno</A><P>
<A HREF="/ed/webmaster/alunos/matricula.phtml">Matricular matérias para um aluno</A><P>
<A HREF="/ed/webmaster/alunos/exibealunos.phtml">Exibir alunos já cadastradas</A><P>
<A HREF="/ed/webmaster/materias/listarmateriasdeumaluno.phtml">Listar todas as matérias de um aluno</A><P>
<A HREF="/ed/webmaster/cursos/listarmateriasdeumcurso.phtml">Listar todas as matérias de um curso</A><P>  
<A HREF="/ed/webmaster/alunos/listaralunosporcurso.phtml">Listar todos os alunos de todos os curso</A><P>
<A HREF="/ed/webmaster/alunos/alterar.phtml">Alterar alunos</A><P>
<A HREF="/ed/webmaster/alunos/excluir.phtml">Excluir alunos</A><P>

<?PHP MostraRodape(); ?>
