<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec("Listagem Alunos Cadastrados por Cursos");
?>

<?PHP

	$conn = pg_Connect("localhost", "5432", "", "", "ed");
	     
	if (!$conn) {
		SaiErro ("Nao foi possivel abrir banco de dados.\n");
	}

    $result = pg_Exec($conn, "Select * from alunos_cursos ORDER BY cod_curso;");
    $num = pg_NumRows($result);
	if ( $num == 0 ) {
	    MostraErro ("Não existe alunos cadastradas nos cursos.");
	} 

    echo "<BR>Listagem ordenada por código do curso:";
    echo "<TABLE BORDER = \"2\">";   
	echo "<TR><TD width=\"5\">Código curso</TD><TD>Curso</TD><TD>Data </TD><TD width=\"5\">Codigo aluno </TD><TD>Aluno</TD></TR>\n";
    for($i = 0; $i < $num; $i++) {
		  $cod_curso= pg_Result($result, $i, "cod_curso");
		  $cod_aluno= pg_Result($result, $i, "cod_aluno");
		  $data_aux= pg_Result($result, $i, "data_matricula_curso");
		  $dmano=explode("-", $data_aux);
		  $d = $dmano[0];
		  $m = $dmano[1];
		  $y = $dmano[2];
		  $data_matricula_curso= date( "d-m-Y", mktime(0, 0, 0, $d, $m , $y));    

		  $resultnome = pg_exec($conn, "select * from cursos where cod_curso = $cod_curso;");
		  $numaux = pg_numrows($resultnome);
		  if($numaux == 0){
			  echo "<BR>Erro 1 - Nada Encontrado.";
			  echo "<BR><form><input type=\"button\" value=\"Retornar\" onClick=\"history.back()\">";
			  echo "</form>";
			  exit;
		  }        
		  $nome_curso =  pg_result($resultnome, 0, "nome");
		  pg_FreeResult($resultnome);   

		  $resultnome = pg_exec($conn, "select * from alunos where cod_aluno = $cod_aluno;");
		  $numaux = pg_numrows($resultnome);
		  if($numaux == 0){
			  echo "<BR>Erro 2 -Nada Encontrado.";
			  echo "<BR><form><input type=\"button\" value=\"Retornar\" onClick=\"history.back()\">";
			  echo "</form>";
			  exit;
		  }        
		  $nome_aluno =  pg_result($resultnome, 0, "nome");
		  pg_FreeResult($resultnome);   

		  echo "<TR><TD>";
		  echo "$cod_curso";
		  echo "</TD><TD>";
		  echo "$nome_curso";
		  echo "</TD><TD>";
		  echo "$data_matricula_curso";
		  echo "</TD><TD>";
		  echo "$cod_aluno";
		  echo "</TD><TD>";
		  echo "$nome_aluno";
		  echo "</TD></TR>";
    }
	echo "</TABLE>";
    pg_Close($conn);
    pg_FreeResult($result);
?>                              
<?PHP MostraRodape(); ?>
