<?PHP 
	 require ( "../lib/ed.bib.phtml");
	 MostraCabec(" Inclusão de professores novos ");
?>

<FORM ACTION="inclusaoproftemp.phtml" METHOD="POST">
<P>Nome do professor:
<INPUT TYPE="text" NAME="nome_professor" SIZE="40"></INPUT>
<P>Titulação do professor:
<INPUT TYPE="text" NAME="titulo_professor" SIZE="40"></INPUT>
<P>Chave de acesso sistema ( 08 digitos ) :
<INPUT TYPE="chave" NAME="chave_professor" SIZE="8"></INPUT>
<P>Senha de acesso sistema ( 08 digitos )
<INPUT TYPE="password" NAME="senha_professor" SIZE="8"></INPUT>

<?
     echo "<BR>Tipo do professor: ";
     echo "<SELECT NAME=\"tipo\">\n";
     echo "<OPTION VALUE=1>Normal";
     echo "<OPTION VALUE=2>Orientador";
     echo "<OPTION VALUE=3>Coordenador de Curso";
     echo "<OPTION VALUE=4>Visitante";
     echo "</SELECT>\n";
     echo "<BR>";
?>     

<P>Email do professor:
<INPUT TYPE="text" NAME="mail_professor" SIZE="50"></INPUT>
<CENTER>
<INPUT TYPE="submit" VALUE="Cadastrar"></INPUT>
<INPUT TYPE="reset" VALUE="Limpar"></INPUT>
</CENTER>
</FORM>

<?PHP MostraRodape(); ?>
