<html>
<head>

<title>ED Professor </title>
<body bgcolor="#FFFFFF">
<h3>ED - Página do Professor </h3>
</head>
Operações:
<hr size=5 align=center>
<a href="../../webmaster/cursos/inclusao.phtml">Criando Cursos</a><p>
<a href="../../webmaster/cursos/adicionarmaterias.phtml">Adicionando matérias nos  Cursos</a><p>
<a href="../../webmaster/cursos/listarmateriascurso.phtml">Listando as  matérias de um Cursos</a><p>
<a href="../../webmaster/materias/inclusao.phtml">Criando Matérias</a><p>
<a href="../../webmaster/agenda/inclusao.phtml">Criando Agenda nas matérias</a><p>
<a href="uploadphp.phtml" >Enviando arquivos para as matérias</a><p>
<a href="../../listas">Manutenção das listas</a><p>
<p>
        
<BR><BR><form><input type="button" value="Retornar" onClick="history.back()"></form>
<hr size=3 align=center>
</html>
