<?PHP 
	 require ( "../lib/ed.bib.phtml");
	 MostraCabec("Página do WebMaster");
?>
Operações: <BR>
<a href="websistema.phtml" >Reativação do Sistema ED </a><p>
<a href="webconfigsistema.phtml" >Configuração do Sistema </a><p>
<a href="webvideoconferencia.phtml" > Manutenção de vídeo conferência </a><p>
<a href="../listas">Manutenção das listas</a><p>
<a href="agenda"> Agenda</a><p>
<a href="alunos"> Alunos</a><p>
<a href="cursos"> Cursos</a><p>
<a href="materias"> Matérias</a><p>
<a href="professores"> Professores</a><p>
<p>
        
<?PHP MostraRodape(); ?>
