<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec(" Alteração de cursos ");
?>

<FORM ACTION="/ed/webmaster/cursos/dbadicionar2.phtml" METHOD="post">      
<?PHP
	$conn = pg_connect("localhost", "5432", "", "", "ed");
	if(!$conn){
		echo "Não Foi possível abrir a base de dados";
		exit;
	}
	$result = pg_exec($conn, "select * from cursos where cod_curso = $codigo_curso;");
	$num = pg_numrows($result);
	if($num == 0){
		echo "<BR>Nada Encontrado."; 
 		echo "<BR><form><input type=\"button\" value=\"Retornar\" onClick=\"history.back()\"></form>";
		exit; 
	}
	echo "Nome do Curso :";
	echo "<INPUT TYPE=\"hidden\" NAME=\"codigo_curso\" VALUE=\"";
	echo pg_result($result, 0, "cod_curso"); echo "\">\n";	
	echo "<INPUT TYPE=\"hidden\" NAME=\"nome_curso\" VALUE=\"";
	echo pg_result($result, 0, "nome"); echo "\">\n";

	echo pg_result($result, 0, "nome");

    pg_FreeResult($result);  

    $result = pg_Exec($conn, "Select * from materias ORDER BY nome;");
    $num = pg_NumRows($result);
    if ( $num == 0 ) {
          MostraErro ("Não existe matérias cadastradas ");
     }
     echo "<BR>Selecione uma Matéria(s):";
     echo "<SELECT NAME=\"codigo_materia\">\n";
     for($i = 0; $i < $num; $i++)
     {
                echo "<OPTION VALUE=\"";
                echo pg_Result($result, $i, "cod_materia");
                echo "\">";
                echo pg_Result($result, $i, "nome");
                echo "\n";
				echo "</OPTION>";
     }
     echo "</SELECT>\n";
     pg_FreeResult($result);  
     pg_Close($conn);


?>
<CENTER><INPUT TYPE="submit" VALUE="acrescentar"></CENTER>
</FORM>
<?PHP MostraRodape(); ?>
