<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec("Exclusão de cursos");

	$conn = pg_Connect("localhost", "5432", "", "", "ed");
	     
	if (!$conn) {
		SaiErro ("Nao foi possivel abrir banco de dados.\n");
	}
		 
	$result = pg_Exec($conn,
                     "delete from cursos 
                      where cod_curso = $codigo;");
	if (!$result) {
                echo "<CENTER><BR><BR>Nada Encontrado<BR><BR></CENTER>";
 		echo "<BR><form><input type=\"button\" value=\"Retornar\" onClick=\"history.back()\"></form>";
                pg_FreeResult($result);
                pg_Close($conn);
                exit;
     }

	echo "<CENTER>";
	echo "<BR><BR>Curso Excluído do Cadastro";
	echo "<BR><BR>";
	echo "<BR><BR>";
	echo "</CENTER>";
	pg_FreeResult($result);
	pg_Close($conn);
	MostraRodape(); 
?>
