<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec("Inclusão de cursos ");
?>
<H2>Resultado</H2>

<?PHP
	$conn = pg_Connect("localhost", "5432", "", "", "ed");
	     
	if (!$conn) {
		echo "Não foi possivel abrir banco de dados.\n";
	exit;
	}
	if($nome_curso == ""){
             	pg_Close($conn);
		MostraErro( "<BR><BR> O campo NOME DO CURSO deve ser preenchido!
		<BR><BR> <BR><BR>");
	}
	if($codigo_professor == ""){
             	pg_Close($conn);
		MostraErro( "<BR><BR> Você deve escolher um professor responsável pelo curso!  <BR><BR> <BR><BR>");
	}
	if($num_max_vagas == ""){
             	pg_Close($conn);
		MostraErro( "<BR><BR> Você deve informar o número máximo de vagas do curso!  <BR><BR> <BR><BR>");
	}
	if($data_final_matricula == ""){
             	pg_Close($conn);
		MostraErro( "<BR><BR> Você deve informar a data final de matricula do curso!  <BR><BR> <BR><BR>");
	}
	if($data_inicio_curso == ""){
             	pg_Close($conn);
		MostraErro( "<BR><BR> Você deve informar a data do inicio do curso!  <BR><BR> <BR><BR>");
	}
	if($data_fim_curso == ""){
             	pg_Close($conn);
		MostraErro( "<BR><BR> Você deve informar a data final do curso!  <BR><BR> <BR><BR>");
	}


    $CURSO = strtoupper($nome_curso);
    $testanome = pg_Exec($conn, "select * from cursos ;");
    $num = pg_NumRows($testanome);
    $i=0;
    for($i = 0; $i < $num; $i++) {
            /* trim() tira os espacos em brancos  do comeco ate o fim da base de dados */
        $nome= strtoupper(trim(pg_Result( $testanome, $i, "nome" )));
        $ret=strcmp ( $nome, $CURSO );
        if ( $ret == 0 ) {
           echo "<BR><BR><BR>Curso $nome_curso já está cadastrado !";
           echo "<BR><form><input type=\"button\" value=\"Retornar\" onClick=\"history.back()\"></form>";
           pg_FreeResult($testanome);          
		   pg_close($conn);
           exit;
       }
    }
    pg_FreeResult($testanome);        

	$result = pg_Exec($conn,
                        "INSERT INTO cursos
                         VALUES ('$nome_curso','$codigo_professor', '$num_max_vagas' , '$data_final_matricula', '$data_inicio_curso', '$data_fim_curso' );");
	if (!$result) {
		echo "Ocorreu um erro durante a inclusao na base de dados.\n";
		exit;
	}

	echo "<CENTER>";
	echo "<BR><BR>curso incluído nas bases de dados";
	echo "</CENTER>";
	pg_FreeResult($result);
	pg_Close($conn);

	/* Criando o diretorio $nome_curso */
	$HOME= Configuracao("DIRHOME");
	$nomedir = sprintf ( "%s/cursos/%s",$HOME,$nome_curso);
	/*echo "<BR>criando diretório do curso ($nomedir)... "; */
	$ret = mkdir ("$nomedir" , 0777 );
        if (!$ret) {
                SaiErro ("<BR>\nOcorreu um erro durante a criaçao do diretorio do curso $nome_curso .\n");
        } 
	$ret = mkdir ("$nomedir/materias" , 0777 );
        if (!$ret) {
                SaiErro ("<BR>\nOcorreu um erro durante a criaçao do diretorio do curso $nomedir/materias .\n");
        } 
	$ret = mkdir ("$nomedir/alunos" , 0777 );
        if (!$ret) {
                SaiErro ("<BR>\nOcorreu um erro durante a criaçao do diretorio do curso $nomedir/alunos .\n");
        } 
	$ret = mkdir ("$nomedir/professores" , 0777 );
        if (!$ret) {
                SaiErro ("<BR>\nOcorreu um erro durante a criaçao do diretorio do curso $nomedir/professores .\n");
        }
	/*echo "<BR>Ok, criado diretório. ";*/

?>
<BR><A HREF="/ed/webmaster/cursos/inclusao.phtml">Cadastrar outro</A>
<?PHP MostraRodape(); ?>
