<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec(" Alteração de cursos ");
	$conn = pg_connect("localhost", "5432", "", "", "ed");
	if(!$conn){
		echo "Não Foi possível abrir a base de dados";
		exit;
	}
	$result = pg_exec($conn, "update cursos set nome = '$curso', cod_professor = '$codigo_professor', num_max_vagas = '$num_max_vagas' , data_final_matricula = '$data_final_matricula' , data_inicio_curso = '$data_inicio_curso' , data_fim_curso = '$data_fim_curso'  where cod_curso = $codigo_curso;");
	$num = pg_numrows($result);
	echo "<BR>Curso Alterado.";
	MostraRodape(); 
?>
