<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec(" Inclusão de cursos ");
?>

<FORM ACTION="/ed/webmaster/cursos/dbinclusao.phtml" METHOD="POST">
<?PHP

	$conn = pg_Connect("localhost", "5432", "", "", "ed");
	     
	if (!$conn) {
		SaiErro ("Nao foi possivel abrir banco de dados.\n");
	}

  /* aqui possu mudar para selecionar  somente os professores 
     onde o tipo = 2 "Coordenador de Curso" */

 $result = pg_Exec($conn, "Select * from professores ORDER BY nome ;");
        $num = pg_NumRows($result);

		if($num == 0)
		{
			echo "<BR><CENTER>ERRO- Atenção - não existem professores Coordenadores de Curso cadastrados!\n";
			echo "<BR>Você deve cadastrar um professor primeiro !\n";
			echo "<BR>Clique no botão Retornar de seu browser 02 vezes, e cadastre um professor, ou entre em contato com o webmaster. </CENTER>\n";
			echo "<BR><form><input type=\"button\" value=\"Retornar\" onClick=\"history.back()\"></form>";
        	pg_Close($conn);
			exit;
		}
	echo " <P>Nome do curso:";
	echo "<INPUT TYPE=\"text\" NAME=\"nome_curso\" SIZE=\"40\"></INPUT> <BR>";
	echo " <P>Número máximo de vagas do curso:";
	echo "<INPUT TYPE=\"text\" NAME=\"num_max_vagas\" SIZE=\"3\"></INPUT> <BR>";
	echo " <P>Data final da matricula (DD/MM/AAAA) :";
        echo "<INPUT TYPE=\"text\" NAME=\"data_final_matricula\" SIZE=\"10\"></INPUT> <BR>";  
	echo " <P>Data início do curso (DD/MM/AAAA) :";
        echo "<INPUT TYPE=\"text\" NAME=\"data_inicio_curso\" SIZE=\"10\"></INPUT> <BR>";  
	echo " <P>Data final do curso (DD/MM/AAAA) :";
        echo "<INPUT TYPE=\"text\" NAME=\"data_fim_curso\" SIZE=\"10\"></INPUT> <BR>";  
	echo "Professor responsável:";
        echo "<SELECT NAME=\"codigo_professor\">\n";

        for($i = 0; $i < $num; $i++)
        {
                echo "<OPTION VALUE=\"";
                echo pg_Result($result, $i, "cod_professor");
                echo "\">"; 
				echo pg_Result($result, $i, "nome");
                echo "\n";
        }
        echo "</SELECT>\n";
	echo "<BR>";
        pg_Close($conn);
        pg_FreeResult($result);
?>                              

<INPUT TYPE="submit" VALUE="Cadastrar"></INPUT>
<INPUT TYPE="reset" VALUE="Limpar"></INPUT>
</FORM>
<?PHP MostraRodape(); ?>
