<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec("Cursos");
?>
<H2>Operações</H2>

<A HREF="/ed/webmaster/cursos/inclusao.phtml">Incluir novo curso</A><P>
<A HREF="/ed/webmaster/cursos/exibecursos.phtml">Exibir cursos já cadastrados</A><P>
<A HREF="/ed/webmaster/cursos/alterar.phtml">Alterar cursos</A><P>
<A HREF="/ed/webmaster/cursos/excluir.phtml">Excluir cursos</A><P>
<A HREF="/ed/webmaster/cursos/adicionarmaterias.phtml">Acrescentar matérias no curso</A><P>
<A HREF="/ed/webmaster/cursos/listarmateriasdeumcurso.phtml">Listar todas as materias de um curso</A><P>
<A HREF="/ed/webmaster/cursos/listarmateriascurso.phtml">Listar todos os cursos e todas as suas matéria</A><P>

<?PHP MostraRodape(); ?>
