<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec("Exclusão de matérias");

	$conn = pg_Connect("localhost", "5432", "", "", "ed");
	     
	if (!$conn) {
		SaiErro( "1Nao foi possivel abrir banco de dados.\n");
	}
		 
	$result = pg_Exec($conn,
                     "delete from agendas 
                      where cod_agenda = $codigo_agenda;");

	//echo "<BR>result=$result><BR>";

	if (!$result) {
                echo "<CENTER>";
                echo "<BR><BR>Nada Encontrado";
                echo "<BR><BR>";
                echo "</CENTER>";
 		echo "<BR><form><input type=\"button\" value=\"Retornar\" onClick=\"history.back()\"></form>";
                pg_FreeResult($result);
                pg_Close($conn);
                exit;
        }
	echo "<CENTER>";
	echo "<BR><BR>Agenda Excluída do Cadastro";
	echo "<BR><BR>";
	echo "<BR><BR>";
	echo "</CENTER>";
	pg_FreeResult($result);
	pg_Close($conn);
	MostraRodape(); 
?>
