<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec(" Alteração de Agenda ");
	$conn = pg_connect("localhost", "5432", "", "", "ed");
	if(!$conn){
		echo "Não Foi possível abrir a base de dados";
		exit;
	}
	$result = pg_exec($conn, "update agendas set data = '$data_agenda', nome = '$nome', cod_materia = '$codigo_materia', tipo_agenda = '$tipo_agenda' where cod_agenda = $codigo_agenda;");
	$num = pg_numrows($result);
	echo "<BR>Agenda Alterada.";
	MostraRodape(); 
?>
