<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec(" Inclusão de Agenda ");
?>

<FORM ACTION="/ed/webmaster/agenda/dbinclusao.phtml" METHOD="POST">
<?PHP

	$conn = pg_Connect("localhost", "5432", "", "", "ed");
	     
	if (!$conn) {
		SaiErro ("Nao foi possivel abrir banco de dados.\n");
	}
    $result = pg_Exec($conn, "Select * from materias ORDER BY nome;");
    $num = pg_NumRows($result);

        if($num == 0)
        {
            echo "<BR><CENTER>ERRO- Atenção - não existem materias cadastradas!\n";
            echo "<BR>Você deve cadastrar uma matéria primeiro !\n";
            echo "<BR><form><input type=\"button\" value=\"Retornar\" onClick=\"history.back()\"></form>";
            pg_Close($conn);
            exit;
        }               



	echo "Escolha uma matéria para incluir a agenda: ";
    echo "<SELECT NAME=\"codigo_materia\">\n";
    for($i = 0; $i < $num; $i++) {
          echo "<OPTION VALUE=\"";
          echo pg_Result($result, $i, "cod_materia");
          echo "\">";
          echo pg_Result($result, $i, "nome");
          echo "\n";
     }
     echo "</SELECT>\n";

	 echo " <P>Data para ser agendado em (DD/MM/AAAA) :";
     echo "<INPUT TYPE=\"text\" NAME=\"data_agenda\" SIZE=\"10\"></INPUT> <BR>";
     echo "<BR>Tipo do texto da agenda";
     echo "<SELECT NAME=\"tipo_agenda\">\n";
     echo "<OPTION VALUE=1>texto normal";
     echo "<OPTION VALUE=2>link";
     echo "<OPTION VALUE=3>aviso de prova";
     echo "<OPTION VALUE=4>arquivo p/ baixar";
     echo "</SELECT>\n";
     echo "<BR>";
	 echo " <P>Descrição do texto da agenda:";
     echo "<INPUT TYPE=\"text\" NAME=\"nome\" SIZE=\"80\"></INPUT> <BR>";

     pg_FreeResult($result);
     pg_Close($conn);
?>                              

<INPUT TYPE="submit" VALUE="Cadastrar"></INPUT>
<INPUT TYPE="reset" VALUE="Limpar"></INPUT>
</CENTER>
</FORM>
<?PHP MostraRodape(); ?>
