<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec("Agenda");
?>
<H2>Operações</H2>

<A HREF="/ed/webmaster/agenda/inclusao.phtml">Incluir nova agenda</A><P>
<A HREF="/ed/webmaster/agenda/exibeagendas.phtml">Exibir agendas já cadastradas</A><P>
<A HREF="/ed/webmaster/agenda/exibeagendas.phtml">Alterar agenda</A><P>
<A HREF="/ed/webmaster/agenda/excluir.phtml">Excluir agenda</A><P>

<?PHP MostraRodape(); ?>
