<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec(" Alteração de Materias ");
	$conn = pg_connect("localhost", "5432", "", "", "ed");
	if(!$conn){
		echo "Não Foi possível abrir a base de dados";
		exit;
	}
	$result = pg_exec($conn, "update materias set nome = '$materia', cod_professor = '$codigo_professor' where cod_materia = $codigo_materia;");
	$num = pg_numrows($result);
	echo "<BR>Matéria Alterada.";
	MostraRodape(); 
?>
