<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec(" Lista de Materias ");

 function MostraProfessor($codigo_prof)
    {
		//echo "codigo_prof=$codigo_prof";
		// aqui vou pegar o nome do professor
		//
		$conn = pg_connect("localhost" , "5432", "","", "ed");
		$query = pg_Connect("localhost", "5432", "", "", "ed");
		if(!$query){
			echo "Não Foi possível abrir a base de dados";
			exit;
		}
		$result1 = pg_exec($query, "select * from professores where cod_professor = $codigo_prof;");
		$num_ocorrencias = pg_numrows($result1);
		if ($num_ocorrencias > 1){
			echo "\n<BR>Atenção - Existe mais de um professor com o mesmo código<BR>";
		}
	 	echo "<TD>";
		// echo "codigo_prof=$codigo_prof";
		echo pg_Result($result1, 0 , "nome");
		echo "</TD>\n" ;
		pg_FreeResult($result1);
		pg_Close($query);

    }        
	

		if(!isset($pos_cursor)){
		$pos_cursor = 0;
		}
		$conn = pg_Connect("localhost", "5432", "", "", "ed");
		if (!$conn) {
			SaiErro("Um erro ocorreu durante a abertura da base de dados.\n");
		}
		TabelaOK($conn,"materias");

		pg_exec($conn,"begin;");
		pg_exec($conn,"declare pont cursor for SELECT * FROM materias ORDER BY nome;");
		if($pos_cursor != 0){
				pg_exec($conn,"move forward $pos_cursor in pont;");
		}
		$result = pg_exec($conn,"fetch 10 in pont;");
		if (!$result) {
			SaiErro("Um erro ocorreu durante a abertura da base de dados.\n");  
		}
		pg_exec($conn,"end;");

		$prox_pag = $pos_cursor + 10;
		$pag_ant = $pos_cursor - 10;

		$todos = pg_exec($conn,"SELECT * FROM materias ORDER BY nome;");
		$total = pg_numrows($todos);
		$paginas = ceil($total/10);
		if(!isset($pag_atual)){ $pag_atual = 1; }
		pg_freeresult($todos);

		echo"<B><BIG>$total Materias. P&aacute;gina $pag_atual/$paginas.</BIG></B><br>";
		$num = pg_NumRows($result);
		$i = 0;
		if($num > 0){
			echo "<HR SIZE=\"2\">";	    
			echo "<TABLE BORDER = \"2\">";
			echo "<TR><TD width=\"4\">Código</TD><TD width=\"20\">Nome da Matéria</TD><TD width=\"20\">Professor responsável</TD><TD>&nbsp</TD></TR>\n";
			while ($i < $num) {
				echo "<FORM METHOD=\"post\" ACTION=\"dbupdate.phtml\">\n";
				echo "<INPUT TYPE=\"hidden\" NAME=\"codigo_materia\" VALUE=\"";echo pg_result($result, $i, "cod_materia"); echo "\">";
				echo "<TD><CENTER>"; echo pg_Result($result, $i, "cod_materia") ; echo "</TD></CENTER>\n" ;
				echo "<TD>";echo pg_Result($result, $i, "nome");echo "</TD>\n" ;
				$codigo_prof = pg_result($result, $i, "cod_professor");

				MostraProfessor($codigo_prof);

				echo "<TD><INPUT TYPE=\"submit\" VALUE=\"Alterar\"></TD>\n" ;
				echo "</TR>\n";
				echo "</FORM>\n";
				$i++;
			}
			echo "</TABLE>";
			//pg_FreeResult($result);
			//pg_Close($conn);
		}
		elseif  ($num == 0) {
			echo "<TR><TD>\n";
			echo "Nada encontrado.\n" ;
			echo "<BR><form><input type=\"button\" value=\"Retornar\" onClick=\"history.back()\"></form>";
			echo "</TR></TD>\n";
			exit;
		}

		echo "<CENTER>\n";
		echo "<TABLE BORDER=0 CELLSPACING=4><TR>\n";
		if($pos_cursor > 0)
		{
		$cont = $pag_atual - 1;
		echo "
		<TD><A HREF=\"exibematerias.phtml?";echo "pos_cursor=$pag_ant&pag_atual=$cont";echo "\">página anterior</A></TD>\n
		";
		}
		if($pag_atual  < $paginas)
		{
		$cont = $pag_atual + 1;
		echo"
		<TD><A HREF=\"exibematerias.phtml?";echo "pos_cursor=$prox_pag&pag_atual=$cont";echo "\">próxima página</A></TD>\n";
		}
		echo "</TR></TABLE>\n";
		echo "</CENTER>\n";

	MostraRodape();
?>
