<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec("Matérias");
?>
<H2>Operações</H2>

<A HREF="/ed/webmaster/materias/inclusao.phtml">Incluir nova matéria</A><P>
<A HREF="/ed/webmaster/materias/exibematerias.phtml">Exibir matérias já cadastradas</A><P>
<A HREF="/ed/webmaster/materias/listarmateriasdeumaluno.phtml">Listar todas as matérias de um aluno</A><P>
<A HREF="/ed/webmaster/cursos/listarmateriasdeumcurso.phtml">Listar todas as matérias de um curso</A><P>
<A HREF="/ed/webmaster/cursos/listarmateriascurso.phtml">Listar todos os cursos e todas as suas matéria</A><P>
<A HREF="/ed/webmaster/cursos/adicionarmaterias.phtml">Acrescentar matéria em um curso</A><P>
<A HREF="/ed/webmaster/materias/alterar.phtml">Alterar matérias</A><P>
<A HREF="/ed/webmaster/materias/excluir.phtml">Excluir matéria</A><P>

<?PHP MostraRodape(); ?>
