<?PHP
	require ( "../lib/ed.bib.phtml");
	MostraCabec("Listas ");
?>  
<HTML>
<BODY BGCOLOR="#FFFFFF">

<H3>Gerenciamento de Listas</H3>
<ol>
<li><A HREF="lista_criacao.phtml">Criar lista</A>
<li><A HREF="lista_exclusao.phtml">Remover lista</A>
<li><A HREF="lista_listar.phtml">Listar as listas cadastradas</A>
<li><A HREF="lista_adm.phtml">Opções avançadas de administração das listas cadastradas</A>
<li>Editar arquivos de mensagem
</ol>
<H3>Gerenciamento de usuários e mensagens das listas</H3>
<ol>
<li><A HREF="lista_usu_inclui.phtml">Incluir Usuários</A>
<li><A HREF="lista_usu_exclui.phtml">Remover Usuários</A>
<li><A HREF="lista_usu_lista.phtml">Listar Usuarios</A>
<li><A HREF="lista_usu_opcoes.phtml">Outras Opções </A>
<li><A HREF="lista_arquivos.phtml">Listar Arquivos da Lista (mensagens da lista até ontem)</A>
</ol>
<hr>
<h5>
<A HREF="http://www.conectiva.com.br">Feito por Conectiva Informática</A>
</h5>

<?PHP MostraRodape(); ?>

</BODY>
</HTML>
