<?PHP
	require ( "../lib/ed.bib.phtml");
	MostraCabec("Listas ");
?>  
<HTML>
<BODY BGCOLOR="#FFFFFF">

<H3>Gerenciamento de usuários e mensagens das listas</H3>
<ol>
<li><A HREF="../listas/lista_usu_inclui.phtml">Cadastramento na lista </A>
<li><A HREF="../listas/lista_usu_lista.phtml">Listar Usuarios</A>
<li><A HREF="../listas/lista_usu_opcoes.phtml">Outras Opções </A>
<li><A HREF="../listas/lista_arquivos.phtml">Listar Arquivos da Lista (mensagens da lista até ontem)</A>
</ol>
<hr>
<h5> <A HREF="http://www.conectiva.com.br">Feito por Conectiva Informática</A> </h5>

<?PHP MostraRodape(); ?>

</BODY>
</HTML>
