<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec("Aprovação de professores ");
?>
<FORM METHOD="POST" ENCTYPE=multipart/form-data ACTION=aprovarnovos.phtml>

<?PHP

	$conn = pg_Connect("localhost", "5432", "", "", "ed");
	     
	if (!$conn) {
		SaiErro ("Nao foi possivel abrir banco de dados.\n");
	}

 $result = pg_Exec($conn, "Select * from professorestemp ORDER BY nome;");
        $num = pg_NumRows($result);

	if ( $num == 0 ) {
		echo "Não existe professores temporarios para aprovação";
		MostraRodape();
		exit;
	}
	echo "<BR>Selecione um Professor Novo:";
        echo "<SELECT NAME=\"codigo_professor\">\n";
        for($i = 0; $i < $num; $i++)
        {
                echo "<OPTION VALUE=\"";
                echo pg_Result($result, $i, "cod_professor");
                echo "\">"; 
				echo pg_Result($result, $i, "nome");
                echo "\n";
        }
        echo "</SELECT>\n";
        pg_Close($conn);
        pg_FreeResult($result);
		echo "<BR>";
		echo "<form> <INPUT TYPE=submit NAME=Acao VALUE=Aprova> ";
		echo "<INPUT TYPE=submit NAME=Acao VALUE=Reprova> <BR> </form>";
?>                              

<?PHP MostraRodape(); ?>
