<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec("Exclusão de Professores"); 

	$conn = pg_Connect("localhost", "5432", "", "", "ed");
	     
	if (!$conn) {
		SaiErro ("Nao foi possivel abrir banco de dados.\n");
	}
		 
	$result = pg_Exec($conn,
                     "delete from professores 
                      where cod_professor = $codigo;");
	if (!$result) {
                echo "<CENTER>";
                echo "<BR><BR>Nada Encontrado";
                echo "<BR><BR>";
                echo "<BR><BR>";
                echo "</CENTER>";
                echo "<BR><BR> <A HREF=\"/ed/webmaster/professores/index.html\">
Volta ao índice</A>";
                pg_FreeResult($result);
                pg_Close($conn);
                exit;
        }

	echo "<CENTER>";
	echo "<BR><BR>Professor Excluído do Cadastro";
	echo "<BR><BR>";
	echo "<BR><BR>";
	echo "</CENTER>";
	pg_FreeResult($result);
	pg_Close($conn);
	MostraRodape(); 
?>
