<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec(" Alteração de Professores ");
?>

<FORM ACTION="/ed/webmaster/professores/dbupdate2.phtml" METHOD="post">      
<?PHP
	$conn = pg_connect("localhost", "5432", "", "", "ed");
	if(!$conn){
		echo "Não Foi possível abrir a base de dados";
		exit;
	}


	$result = pg_exec($conn, "select * from professores where cod_professor = $codigo_professor;");
	$num = pg_numrows($result);
	if($num == 0){
		echo "<BR>Nada Encontrado."; 
		exit; }
	echo "<INPUT TYPE=\"hidden\" NAME=\"codigo_professor\" VALUE=\"";
	echo pg_result($result, 0, "cod_professor"); echo "\">\n";	
	echo "<P>Professor:";
	echo "<INPUT TYPE=\"text\" SIZE=\"30\" NAME=\"professor\" VALUE=\"";
	echo pg_result($result, 0, "nome"); echo "\">\n";	
	echo "<P>Titulação:";
	echo "<INPUT TYPE=\"text\" SIZE=\"30\" NAME=\"titulo\" VALUE=\"";
	echo pg_result($result, 0, "titulo"); echo "\">\n";	
	echo "<P>Chave:";
	echo "<INPUT TYPE=\"hidden\" NAME=\"chave\" VALUE=\"";
	echo pg_result($result, 0, "chave"); echo "\">\n";	
	echo pg_result($result, 0, "chave");

	echo "<P>Senha:";
	echo "<INPUT TYPE=\"text\" SIZE=\"8\" NAME=\"senha\" VALUE=\"";
	echo pg_result($result, 0, "senha"); echo "\">\n";	

	$tipo=pg_result($result, 0, "tipo"); 
	echo "<BR>Tipo :";
	echo "<SELECT NAME=\"tipo\">\n";
	if ( $tipo == '1' ) {
		echo "<OPTION SELECTED VALUE=1>Normal";
	}
	else {
		echo "<OPTION VALUE=1>Normal";
        } 
	if ( $tipo == '2' ) {
		echo "<OPTION SELECTED VALUE=2>Orientador";
	}
	else {
		echo "<OPTION VALUE=2>Orientador";
        } 
	if ( $tipo == '3' ) {
		echo "<OPTION SELECTED VALUE=3>Coordenador de Curso";
	}
	else {
		echo "<OPTION VALUE=3>Coordenador de Curso";
        } 
	if ( $tipo == '4' ) {
		echo "<OPTION SELECTED VALUE=4>Visitante";
	}
	else {
		echo "<OPTION VALUE=4>Visitante";
        } 
	echo "</SELECT>\n";       

	echo "<P>Email:";
	echo "<INPUT TYPE=\"text\" SIZE=\"30\" NAME=\"email\" VALUE=\"";
	echo pg_result($result, 0, "email"); echo "\">\n";	
?>
<CENTER><INPUT TYPE="submit" VALUE="Alterar"></CENTER>
</FORM>
<?PHP MostraRodape(); ?>
