<?PHP 
	 require ( "../../lib/ed.bib.phtml");
	 MostraCabec("Professores ");
?>
<H2>Operações</H2>

<A HREF="/ed/webmaster/professores/inclusao.phtml">Incluir novo professor</A><P>
<A HREF="/ed/webmaster/professores/aprovar.phtml">Aprovar professor novo</A><P>
<A HREF="/ed/webmaster/professores/exibeprofessores.phtml">Exibir professores já cadastradas</A><P>
<A HREF="/ed/webmaster/professores/alterar.phtml">Alterar professores</A><P>
<A HREF="/ed/webmaster/professores/excluir.phtml">Excluir professor</A><P>
<?PHP MostraRodape(); ?>
